name: publish action
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: setup scala
        uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11
      - name: publish to Bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_TOKEN }}
        run: sbt api/publish
      - name: tag release  
        uses: anothrNick/github-tag-action@1.17.2
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

