name: publish action
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11
      - name: publish to Bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_TOKEN }}
        run: sbt api/publish
  tag:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
